version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: php82test
    ports:
      - 8000:80
      # enplacement du www sur le serveur apache comme dans xxamp
    volumes:
      - ./php:/var/www/html
    build:
      context: .
      dockerfile: DockerFile
  db:
    image: mysql:8.1
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - 3307:3306
  
  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1 
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 
    ports:
      - 8081:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # MailHog web interface port

  